trigger:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: git
      name: UsaLibraries/BuildTemplates

jobs:
- template: library-common-pipeline.yml@templates